### PR TITLE
Fix the variable name

### PR DESCRIPTION
**Pull request by yutkat**

### CODE REVIEW

**Comment by Decodetalkers** [comment]
看到了，不过问题似乎不是出现在这里，我之前把保存的buf，放status里了，忘记更改了

**Comment by Decodetalkers** [comment]
这个地方是给新的置顶的buf绑定的快捷键，你看到下面也有个绑定的快捷键

**Comment by Decodetalkers** [comment]
没想到这都能正常运行.。。绑定了nil这么久

**Comment by Decodetalkers** [comment]
你看看是不是解决了你的问题了

**Comment by yutkat** [comment]
I think it's not fixed... 

When I open the csv file, I get the following message
```
Error detected while processing FileType Autocommands for "csv":
E5108: Error executing lua ...im/site/pack/packer/start/csv-tools.lua/lua/csvtools.lua:165: Expected Lua number
stack traceback:
        [C]: in function 'nvim_buf_set_keymap'
        ...im/site/pack/packer/start/csv-tools.lua/lua/csvtools.lua:165: in function 'add_mappings'
        [string ":lua"]:1: in main chunk
Error detected while processing VimEnter Autocommands for "*":
```

my neovim version: NVIM v0.7.0-dev+1160-g01139ec82
csv-tools version: cb6a284d7f5596499d73052682cb3261b2cfdbb5

**Comment by Decodetalkers** [comment]
> I think it's not fixed...
> 
> When I open the csv file, I get the following message
> 
> ```
> Error detected while processing FileType Autocommands for "csv":
> E5108: Error executing lua ...im/site/pack/packer/start/csv-tools.lua/lua/csvtools.lua:165: Expected Lua number
> stack traceback:
>         [C]: in function 'nvim_buf_set_keymap'
>         ...im/site/pack/packer/start/csv-tools.lua/lua/csvtools.lua:165: in function 'add_mappings'
>         [string ":lua"]:1: in main chunk
> Error detected while processing VimEnter Autocommands for "*":
> ```
> 
> my neovim version: NVIM v0.7.0-dev+1160-g01139ec82 csv-tools version: [cb6a284](https://github.com/chen244/csv-tools.lua/commit/cb6a284d7f5596499d73052682cb3261b2cfdbb5)

I foget to update the mainwindowbuf in line 161, I think this will fix
https://github.com/chen244/csv-tools.lua/commit/26aa86c7c14c9f58c49720648983f5f8272c65de
This commit will fix I think

**Comment by yutkat** [comment]
Hmmm, I still get a nil value of Status.buf in my environment.

**Comment by Decodetalkers** [comment]
> Hmmm, I still get a nil value of Status.buf in my environment.

I see, I make a mistake.. And I need fix more things

**Comment by Decodetalkers** [comment]
> Hmmm, I still get a nil value of Status.buf in my environment.

https://github.com/chen244/csv-tools.lua/commit/e31d615e556ddb6bcdaad5e6e77a3fb462707091

What about this one

**Comment by yutkat** [comment]
It worked fine! Thank you.

**Comment by Decodetalkers** [comment]
> It worked fine! Thank you.

Because before I want to move status out of M, but still some forget. haha.

**Pull request closed without merging**
